server:
  port: 8080

spring:
  application:
    name: taskservice
  cache:
    type: caffeine

task:
  file:
    base-path: ../Tasks

cache:
  task:
    maximum-size: 5

logging:
  level:
    com.example.taskservice: INFO
    org.springframework.cache: INFO

management:
  endpoints:
    web:
      exposure:
        include: health


