server:
  port: 8080

spring:
  application:
    name: taskservice
  cache:
    type: caffeine
task:
  file:
    base-path: /app/Tasks

cache:
  task:
    maximum-size: 5

logging:
  level:
    com.example.taskservice: INFO
    org.springframework.cache: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      cors:
        allowed-origins: 
          - "http://localhost:8080"
          - "https://api.taskservice.com"
          - "https://taskservice.com"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always

# OpenAPI Configuration for Production
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: false
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: TaskService API
  show-actuator: false
  use-management-port: false

# Production info
info:
  app:
    name: TaskService
    description: REST API for Task Management with Caching
    version: 1.0.0
    environment: production 