server:
  port: 8080

spring:
  application:
    name: taskservice
  cache:
    type: caffeine
task:
  file:
    base-path: ../Tasks

cache:
  task:
    maximum-size: 5

logging:
  level:
    com.example.taskservice: DEBUG
    org.springframework.cache: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    # CORS configuration for Swagger UI
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: TaskService API
  show-actuator: true
  use-management-port: false


